on:
  push:
    branches:
      - main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDFs 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      - name: Render
        run: |
          quarto render GitHub-Guide.qmd --to titlepage-pdf
          cp GitHub-Guide.qmd index.qmd
        shell: bash

      - name: Add pdf to main repo
        run: |
          git add GitHub-Guide.pdf
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'update PDF'
          
      - name: Push to destination branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions


